version: "3.9"

services:
  zavodych:
    build: .
    container_name: zavodych
    ports:
      - "15526:15526"
    environment:
      - NODE_ENV=production
      - PORT=15526
      - JWT_SECRET=${JWT_SECRET:-your_secret_here_change_in_production}
      - SMTP_HOST=${SMTP_HOST:-smtp.mailtrap.io}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-your_user}
      - SMTP_PASS=${SMTP_PASS:-your_pass}
      - AI_API_KEY=${AI_API_KEY:-AQVN2-XKmseEFKDZJJyJk0OmvpU3MJn0xufvvzis}
      - AI_API_URL=${AI_API_URL:-https://ai.api.cloud.yandex.net/v1/chat/completions}
      - AI_API_MODEL=${AI_API_MODEL:-gpt://b1g7q3l95b534eaueb63/yandexgpt-lite/latest}
    restart: unless-stopped